package com.saanacode.bankofdaniel.dto;

public enum ErrorCode {

    ACCOUNT_BALANCE_UPDATE_FAILED,
    CONSTRAINT_VIOLATION,
    INSUFFICIENT_BALANCE,
    CURRENCY_CODE_MISMATCH,
    WALLET_DOES_NOT_EXIST,
    ACCOUNT_DOES_NOT_EXIST,
    EMAIL_ALREADY_IN_USE,
    INVALID_CREDENTIALS,
    INVALID_INPUT_PROVIDED,
    INVALID_TOKEN,
    MISSING_TOKEN,
    TOKEN_EXPIRED
}
